#! /bin/sh

picom &
sxhkd &
wal -R

. "${HOME}/.cache/wal/colors.sh"


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	3
bspc config window_gap           	5

# Set the border colors.
bspc config normal_border_color 	"$color1"
bspc config active_border_color 	"$color2"
bspc config focused_border_color 	"$color15"
bspc config presel_feedback_color 	"$color1"

bspc config focus_follows_pointer	true
bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

nm-applet &
